In [13]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
a = np.array([2,4,3,6,7,9])#creating array
a

array([2, 4, 3, 6, 7, 9])

In [3]:
a.ndim #checking dimensions

1

In [4]:
a = np.array([[2,7,89,34,5],[3,5,7,45,57]])
a

array([[ 2,  7, 89, 34,  5],
       [ 3,  5,  7, 45, 57]])

In [5]:
a.ndim

2

In [19]:
#creating 3 dimensional array
a = np.array([[[23,6,67,34,8],[3,89,56,349,9],[34,90,23,56,89]]])
a

array([[[ 23,   6,  67,  34,   8],
        [  3,  89,  56, 349,   9],
        [ 34,  90,  23,  56,  89]]])

In [21]:
a.ndim

3

## Zero's and One's

In [23]:
vaar1 = np.zeros(10)
vaar1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
vaar2 = np.ones(15)
vaar2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
vaar3 = np.ones([2,4,5])
vaar3

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [29]:
vaar3 = np.zeros([3,3,3])
vaar3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# Functions

In [31]:
arr1 = np.array([12,90,45,32,1])
arr1

array([12, 90, 45, 32,  1])

In [32]:
type(arr1)

numpy.ndarray

In [33]:
arr1.argmax()

1

In [34]:
arr1.argmin()

4

In [36]:
arr1.size

5

In [38]:
arr1[3]

32

In [39]:
arr1

array([12, 90, 45, 32,  1])

In [40]:
arr1[2]

45

In [41]:
arr1[0:-1]

array([12, 90, 45, 32])

In [42]:
arr1[-1]

1

In [44]:
arr1[::-1]

array([ 1, 32, 45, 90, 12])

In [45]:
arr1[:-1]

array([12, 90, 45, 32])

In [46]:
arr1[-1:-4]

array([], dtype=int32)

In [47]:
arr1[-1:-3]

array([], dtype=int32)

In [48]:
arr1[1:3]

array([90, 45])

In [50]:
#creating an array of size 5 and with float data type
arr2 = np.array([23,89,44.1,45,23])
arr2

array([23. , 89. , 44.1, 45. , 23. ])

In [51]:
type(arr2)

numpy.ndarray

In [52]:
arr2.dtype

dtype('float64')

In [53]:
arr2.size

5

In [60]:
#create an two dimensional array
#four arrays in the external array
#it should have two elements each

a = np.array([[1,2],[3,4],[5,6],[7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [61]:
a.ndim

2

# Resize and Reshape

In [62]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
arr3 = np.arange(12).reshape(4,3)
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
x =np.array([3,78,65,45,23,90])
x


array([ 3, 78, 65, 45, 23, 90])

In [70]:
q = arr.reshape(6,2)
q

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [78]:
q.shape

(6, 2)

In [72]:
x.max()

90

In [74]:
x.min()

3

In [75]:
np.sqrt(x)

array([1.73205081, 8.83176087, 8.06225775, 6.70820393, 4.79583152,
       9.48683298])

In [76]:
np.log(x)

array([1.09861229, 4.35670883, 4.17438727, 3.80666249, 3.13549422,
       4.49980967])

In [77]:
np.exp(x)

array([2.00855369e+01, 7.49841700e+33, 1.69488924e+28, 3.49342711e+19,
       9.74480345e+09, 1.22040329e+39])

# Transpose

In [80]:
r = np.arange(16).reshape(8,2)
r

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [82]:
transpose = r.T
transpose

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [ 1,  3,  5,  7,  9, 11, 13, 15]])

# floor and ceil

In [83]:
arr = np.array([1.4,55.4,78.9,34.9,44.5])
arr

array([ 1.4, 55.4, 78.9, 34.9, 44.5])

In [85]:
np.floor(arr)

array([ 1., 55., 78., 34., 44.])

In [86]:
np.ceil(arr)

array([ 2., 56., 79., 35., 45.])

In [89]:
rounding = np.round(arr)
rounding

array([ 1., 55., 79., 35., 44.])

# stacking

In [98]:
#vertical stacking same columns
arr1 = np.arange(10).reshape(2,5)
arr2 = np.arange(20).reshape(4,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [99]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [100]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [101]:
#horizontal stacking same no of rows
arr3 = np.arange(15).reshape(3,5)
arr4 = np.arange(18).reshape(3,6)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [102]:
arr4

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [103]:
np.hstack((arr3,arr4))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9,  6,  7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14, 12, 13, 14, 15, 16, 17]])

# array split

In [104]:
#create an array with the shape of 20,10 and split it into 2
arr5 = np.arange(200).reshape(20,10)
arr5

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [105]:
np.shape(arr5)

(20, 10)

In [106]:
np.hsplit(arr5,2)

[array([[  0,   1,   2,   3,   4],
        [ 10,  11,  12,  13,  14],
        [ 20,  21,  22,  23,  24],
        [ 30,  31,  32,  33,  34],
        [ 40,  41,  42,  43,  44],
        [ 50,  51,  52,  53,  54],
        [ 60,  61,  62,  63,  64],
        [ 70,  71,  72,  73,  74],
        [ 80,  81,  82,  83,  84],
        [ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114],
        [120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144],
        [150, 151, 152, 153, 154],
        [160, 161, 162, 163, 164],
        [170, 171, 172, 173, 174],
        [180, 181, 182, 183, 184],
        [190, 191, 192, 193, 194]]),
 array([[  5,   6,   7,   8,   9],
        [ 15,  16,  17,  18,  19],
        [ 25,  26,  27,  28,  29],
        [ 35,  36,  37,  38,  39],
        [ 45,  46,  47,  48,  49],
        [ 55,  56,  57,  58,  59],
        [ 65,  66,  67,  68,  69],
        [ 75,  76,  77,  78,  79],
        [ 85,  86,